### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by WastonHsu** [WaferJay/exam#1]
您好，我最近也在做这个系统，您方便交流一下吗？

**Comment by WaferJay** [comment]
你好。感谢你的issue。当然乐意交流了。

实际上，你也看得出来。这个项目实际上搁置很长时间了。主要是一直都没有时间，并且还没有确定好需求。说不准可以从你这有所收获。

**Comment by WastonHsu** [comment]
> @WastonHsu 你好。感谢你的issue。当然乐意交流了。
> 
> 实际上，你也看得出来。这个项目实际上搁置很长时间了。主要是一直都没有时间，并且还没有确定好需求。说不准可以从你这有所收获。

**Comment by WastonHsu** [comment]
哈哈，我还正在学Flask，目标就是做这么一个东西，现在也有点想法，既然您早有打算，github上类似的Flask项目寥寥无几，还是希望能跟您学习一下，方便留联系方式吗（如果您怕泄露联系方式，可以直接+我，wx：599535303）

**Comment by WaferJay** [comment]
添加了。不过联系方式早已在commit里泄露了。。。
